#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  5 10:56:03 2018

@author: jj
"""
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
import scipy.optimize as spo

def z_function(params):
    x = params[0]
    y = params[1]
    return np.sin(x) + .05 * x ** 2 + np.sin(y) + .05 * y **2

fig = plt.figure()
ax = fig.gca(projection='3d')


# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
Z = z_function((X,Y))


surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

output = True
opt = spo.brute(z_function, ((-5,5,.25), (-5,5,.25)) , full_output=True)
print(opt)
print("The global min is located at ")
print(opt[0])
print("The global min function value is ")
print(opt[1])

local_opt = spo.fmin(z_function, opt[0], xtol = .001, ftol = .001, maxiter = 1000, full_output = True, disp = True)

print("The local min is located at ")
print(local_opt[0])
print("The local min function value is ")
print(local_opt[1])