#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 12 13:17:18 2018

@author: jj
"""

def k_folds(indices, K):
    # write your code in Python 3.6
    output = []
    
    for k_fold in range(K):
        
        training = []
        validation = []
        
        for i,x in enumerate(indices):
            if i % K != k_fold:
                training.append(x)
            if i % K == k_fold:
                validation.append(x)
        output.append(training)
        output.append(validation)
        
    return output

if __name__ == '__main__':
    
    rets  = [.02,.04,-.01,0.0,4.23]
    k =2

    indices = []
    for i,x in enumerate(rets):
        indices.append(i)
    
    out = k_folds(indices, 2)
    print(out)
    
    
        



